/*
 * Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
 * 
 * On Tue Feb  4 15:26:50 IST 2020
 * 
 */
extern "C" {
  unsigned int positAdd16(unsigned int , unsigned int );
}
