/*
 * Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
 * 
 * On Tue Feb  4 15:26:41 IST 2020
 * 
 */
#ifndef __vpi_wrapper_positAdd16_h__
#define __vpi_wrapper_positAdd16_h__

#include <vpi_user.h>

/* registration function */
void positAdd16_vpi_register();

/* VPI wrapper function */
PLI_INT32 positAdd16_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_positAdd16_h__ */
